version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_NON_ROOT_USERNAM: test
      MONGO_NON_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db

  shortenerurl:
    build:
      context: ../
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dspring.data.mongodb.uri=mongodb://test:test@mongo:27017/local?authSource=admin&authMechanism=SCRAM-SHA-1 -Dnewrelic.config.app_name=v1/shortenerurl -Dnewrelic.config.license_key="
    depends_on:
      - mongo